name: "s3 cache"
author: tespkg
description: "S3 actions cache with actions/cache@v2 passthrough"
inputs:
  endpoint:
    description: "s3 / minio endpoint, see: https://docs.min.io/docs/javascript-client-api-reference.html"
    required: false
    default: s3.amazonaws.com
  region:
    description: "AWS region"
    required: false
  port:
    description: minio port
    required: false
  insecure:
    description: use insecure http connection to minio
    required: false
  accessKey:
    description: s3 / minio accessKey
    required: true
  secretKey:
    description: s3 / minio secretKey
    required: true
  sessionToken:
    description: s3 session token - required when using role
    required: false
  bucket:
    description: s3 / minio bucket
    required: true
  path:
    description: "A list of files, directories, and wildcard patterns to cache and restore"
    required: true
  key:
    description: "An explicit key for restoring and saving the cache"
    required: true
  restore-keys:
    description: "An ordered list of keys to use for restoring the cache if no cache hit occurred for key"
    required: false
  use-exact-key-match:
    description: "Do not restore cache with the 'restore-keys' option when no cache hit occurred for 'key'"
    required: false
    default: "false"
  use-fallback:
    description: "Use github actions/cache as fallback"
    required: false
    default: "true"
  use-repository-prefix:
    description: "Prefix the key and restore keys with repository name"
    required: false
    default: "false"
  read-only:
    description: "Read only mode, do not save cache"
    required: false
    default: "false"
  force-save:
    description: "Save cache even if key is matched"
    required: false
    default: "false"
  # zip-option:
  #   description: zip options
  #   required: false
  #   default: -ryq
  # unzip-option:
  #   description: unzip options
  #   required: false
  #   default: -n
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
runs:
  using: node16
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success()"
branding:
  icon: "archive"
  color: "gray-dark"
